### ISSUE TITLE
Custom mux router

### ISSUE THREAD

**Issue by rbsns** [goanywhere/rex#2]
Hi!

There's any way to register custom mux routers to Rex app? The `server.mux` is not exported and can't be modified.

I need to use subdomain at routes (using the `mux.Host()`) to access it's value inside views (using `mux.Vars`), e.g.:

```
app := rex.New()
router := mux.NewRouter().Host("{customer:[a-z]+}.test.com").Subrouter()
router.HandleFunc("/", indexHandler)
```

I want to do something like this:
`app.Mux = router`

Or maybe something more idiomatic:
`app.Router = router`

Best regards!

**Comment by jimzhan** [comment]
Thanks @rsec I've added Host supports into it :-)

**Comment by rbsns** [comment]
Awesome, thanks!!
